name: food_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  adaptive_theme: ^3.5.0
  zoom_tap_animation: ^1.1.0
  mask_text_input_formatter: ^2.8.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/font/
    - assets/svg/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Black.ttf
        - asset: assets/font/Inter-Bold.ttf
        - asset: assets/font/Inter-ExtraBold.ttf
        - asset: assets/font/Inter-ExtraLight.ttf
        - asset: assets/font/Inter-Light.ttf
        - asset: assets/font/Inter-Medium.ttf
        - asset: assets/font/Inter-SemiBold.ttf
        - asset: assets/font/Inter-Thin.ttf
    - family: Viga
      fonts:
        - asset: assets/font/Viga-Regular.ttf